### ISSUE TITLE
SGF parser

### ISSUE THREAD

**Issue by tylerjw** [tylerjw/badukpy#1]
SGF parser (SGF is the standard format for Go games. Using SGF as source for positions and games will not only add a basic functionality to our GUI but also provide an easier way to test our back-end -- test positions can be given through a common format rather than having to figure out our internal datastructure everytime). There's python SGF parsers out there we can use, to implement our own blend would be very time-consuming. Check this out when you have time http://gotools.sourceforge.net/sgflib/

**Comment by tylerjw** [comment]
Checkout the latest additions to simple_go and see what you think...

**Comment by sphaso** [comment]
There's still quite a conundrum with the move_history, board_history and now we have game_tree. Do we need all of these? make_move is appending Nodes on the trunk? am I understanding this correctly?

**Comment by tylerjw** [comment]
The new version works with the AB and AW properties that pre-set board
positions.  Many of the features of SGF are not implemented but they should
be simple to implement.

As far as removing all the other methods of board history, we should see
what uses what and reduce to just the game_tree if we can.

On Sat, Jul 13, 2013 at 7:06 PM, sphaso notifications@github.com wrote:

> There's still quite a conundrum with the move_history, board_history and
> now we have game_tree. Do we need all of these? make_move is appending
> Nodes on the trunk? am I understanding this correctly?
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tylerjw/badukpy/issues/1#issuecomment-20920734
> .

## 

V/R
Tyler Weaver
Cell - (303) 903-5681
email - tylerjw@gmail.com

"Things may come to those who wait, but only the things left by those who
hustle."
- Abraham Lincoln

**Comment by tylerjw** [comment]
The basics are included and the details will be filled in as we go.  I'm closing this issue.
