### ISSUE TITLE
PASS_MOVE bug

### ISSUE THREAD

**Issue by tylerjw** [tylerjw/badukpy#11]
``` python
    def pass_move(self,evt=None):
        self.make_move(PASS_MOVE)
```

When you pass the move isn't registering because the other side does not play.  When you go to click on another location you continue play as black instead of white.

**Comment by sphaso** [comment]
Cannot reproduce. Opening the GUI I start playing as WHITE. When I pass, my next stone is BLACK. The problem is that the computer is not playing after I pass, but this is a problem inside a mock function.

**Comment by tylerjw** [comment]
I found the issue, I thought it was a problem with the backend and dug into the code looking for a bug.  Solution was simple:

``` python
    def pass_move(self,evt=None):
        self.make_move(PASS_MOVE)
        move = self.game.generate_move()
        self.make_move(move)
```

**Comment by sphaso** [comment]
Doesn't this assume that the user is passing in a game against the computer?

**Comment by tylerjw** [comment]
Yes, but since the user is currently playing against the computer, that makes sense right?

**Comment by sphaso** [comment]
It does :) we should remember to change it once we have a more functional
GUI
