### ISSUE TITLE
test_ponnuki fails on asserting legal move

### ISSUE THREAD

**Issue by sphaso** [tylerjw/badukpy#5]
test_ponnuki (ponnuki is a 4 stones diamond shape) is failing after asserting the legality of a move, said move plays a stone of the opposite color right at the center of the formation which is obviously suicide.
Either there's a bug in the test or in legal(self, pos, change_side) function.

**Comment by tylerjw** [comment]
The bug was in the test script.  The board object (self.board) is not a reference to the current board in self.game.

Up until the test you were changing self.board.  The test was made in self.game.  Note changes in version pushed.
