### ISSUE TITLE
territory of group surrounding unconditionally alive group

### ISSUE THREAD

**Issue by tylerjw** [tylerjw/badukpy#7]
This demonstrates a problem in the territory algorithm:

``` python
'''
   ABCDEFGHJKLMN
  +-------------+
13|.............|13
12|.............|12
11|XXXXXXXXXX...|11
10|X.........X..|10
 9|X.........X..| 9
 8|X.OOOOO...X..| 8
 7|X.O.O.OO..X..| 7
 6|X.OOOOOO..X..| 6
 5|X.O....O..X..| 5
 4|X.O....O..X..| 4
 3|X.OOOOOO..X..| 3
 2|X.........X..| 2
 1|XXXXXXXXXXX..| 1
  +-------------+
   ABCDEFGHJKLMN
'''
test = (4,7) not in territory
self.assertEqual(test, True) #(4,7) - D7 not in Black territory (white eye)
```

Currently the test fails, as (4,7) is shown to be counted as black territory.

**Comment by sphaso** [comment]
Yes, the code is very naive, I'll fix it ASAP

**Comment by tylerjw** [comment]
I think you were on the right track testing for territory inside a group.  Just looking at the diagram made me think of a case were it wouldn't work.

**Comment by sphaso** [comment]
this test is passing, there might be other edge cases to think about (corners, strangely shaped groups...)
